* gqoco
** a simple GraphQL code generator (to TS)

=0=: Some graphQL code generator are so convoluted
that you need to install the entire npm repository
and configure options in their own file definition
(one day JS, the next one yaml, TS on the third,
and docs gets out of sync in between...) just to
get a single line of code out a GraphQL file.

Reason is, people are lazy, and their lazyness
drags other lazy coders into this vortex, this
creates mass, that in turns starts to drag the
non-lazy ones into it.

Inside of the vortex, LOT of efforts are put in
the hope that this will "make the community
stronger" (meaning: to get out of this deep shit,
we promise). In the end, the stadium crumbles: 
everybody entered excited, and get out angry...
when not stuck.

The added collective effort to *find* a reasonable
solution is superior to the demands of
the people whirling and yelling for help and support
inside the vortex. Add to this the cost of the way
back ticket (Where we are when we got lost).
This way. =goto 0=.

